import { create } from 'zustand'
import { persist } from 'zustand/middleware'

export type Language = 'id' | 'en'

export const translations = {
  id: {
    dashboard: "Dashboard",
    dashboardSubtitle: "Ringkasan keuangan Anda hari ini.",
    totalBalance: "Total Saldo",
    income: "Pemasukan",
    expense: "Pengeluaran",
    cashFlow: "Arus Kas",
    recentTransactions: "Transaksi Terakhir",
    history: "Riwayat Transaksi",
    historySubtitle: "Daftar lengkap semua transaksi Anda.",
    allTransactions: "Semua Transaksi",
    date: "Tanggal",
    category: "Kategori",
    note: "Catatan",
    amount: "Nominal",
    noTransactions: "Belum ada transaksi.",
    quickEntry: "Entry Cepat",
    addNewTransaction: "Tambah Transaksi Baru",
    modalDesc: "Masukkan detail transaksi hari ini.",
    amountLabel: "Nominal (Rp)",
    categoryLabel: "Kategori",
    noteLabel: "Catatan",
    categoryPlaceholder: "Makanan, Transport, dll",
    notePlaceholder: "Makan siang",
    cancel: "Batal",
    save: "Simpan Transaksi",
    today: "Hari ini",
    yesterday: "Kemarin",
    daysAgo: "Hari lalu",
    currentTotal: "Total saat ini",
    overallTotal: "Total keseluruhan",
    initialBalance: "Saldo Awal",
    initialNote: "Modal awal",
    livePreview: "Pratinjau Nominal:",
    inputNumberWarning: "Silakan masukkan angka saja",
    planning: "Perencanaan",
    planningSubtitle: "Kelola batas anggaran & target tabungan Anda.",
    statistics: "Statistik",
    statisticsSubtitle: "Analisis grafik arus kas & pengeluaran Anda.",
    netWorth: "Kekayaan Bersih",
    totalInvestment: "Total Investasi",
    cashBalance: "Saldo Tunai",
    portfolioAsset: "Total Portofolio & Aset",
    stocks: "Saham",
    crypto: "Kripto",
    initialCapital: "Modal Awal",
    realizedGainLoss: "Realized Gain / Loss",
    netInvestmentValue: "Nilai Bersih Investasi",
    profit: "Untung",
    loss: "Rugi",
    updatePortfolio: "Perbarui Portofolio",
    weeklyReminder: "Pengingat Mingguan",
    weeklyReminderDesc: "Perbarui nilai realized gain/loss investasi Saham & Kripto Anda minggu ini untuk kalkulasi kekayaan bersih yang akurat.",
    lastUpdated: "Terakhir diperbarui",
    budgetLimit: "Batas Anggaran",
    savingGoals: "Target Tabungan",
    cashFlowTrend: "Tren Arus Kas (Pemasukan vs Pengeluaran)",
    topExpenses: "Top Pengeluaran",
    activeLabel: "Aktif",
    targetLabel: "Target",
    collectedLabel: "Terkumpul",
    remainingLabel: "Sisa",
    saveChanges: "Simpan Perubahan",
    incomeVsExpense: "Pemasukan vs Pengeluaran",
    loading: "Memuat...",
    addAsset: "Tambah Aset Baru",
    assetName: "Nama Aset",
    assetType: "Tipe Aset",
    otherType: "Lainnya",
    weeklyRecommended: "Rekomendasi Update Mingguan",
    noAssets: "Belum ada aset investasi.",
    deleteAssetConfirm: "Hapus aset ini?",
    editAsset: "Edit Aset",
    newAsset: "Aset Baru",
    allAssetsDetail: "Rincian Detail Portofolio & Aset",
    addBudget: "Tambah Anggaran",
    editBudget: "Edit Anggaran",
    deleteBudgetConfirm: "Hapus anggaran ini?",
    budgetCategory: "Kategori Anggaran",
    budgetAmount: "Batas Anggaran (Rp)",
    addGoal: "Tambah Target Tabungan",
    editGoal: "Edit Target Tabungan",
    deleteGoalConfirm: "Hapus target tabungan ini?",
    goalTitle: "Nama Target Tabungan",
    goalTarget: "Nominal Target (Rp)",
    goalCollected: "Nominal Terkumpul (Rp)",
    goalIcon: "Pilih Ikon",
    emptyBudgets: "Belum ada batas anggaran. Atur batas anggaran bulanan Anda untuk menghindari pengeluaran berlebih.",
    emptyGoals: "Belum ada target tabungan. Tentukan target impian Anda dan lacak pencapaian tabungan Anda secara berkala.",
    newBudget: "Batas Anggaran Baru",
    newGoal: "Target Tabungan Baru",
    allBudgets: "Kelola Batas Anggaran",
    allGoals: "Kelola Target Tabungan",
    deleteConfirm: "Apakah Anda yakin ingin menghapus ini?",
    deleteBudget: "Hapus Anggaran",
    deleteGoal: "Hapus Target",
    deductFromCash: "Kurangi dari Saldo Tunai",
    deductHelp: "Mengurangi saldo tunai aktif Anda untuk modal awal aset.",
    glAdjustNote: "Selisih realized gain/loss akan dicatat otomatis sebagai transaksi.",
    liquidateConfirm: "Opsi Penghapusan & Likuidasi Aset",
    liquidateDesc: "Nilai bersih aset saat ini adalah [nilai]. Apakah Anda ingin melikuidasi sisa nilai ini kembali ke Saldo Tunai (mencatat transaksi Pemasukan)?",
    liquidateOption: "Ya, Likuidasi ke Saldo Tunai",
    deleteOnlyOption: "Hapus Saja (Tanpa Likuidasi)",
    glAdjustIncomeNote: "Penyesuaian Investasi (Untung): [Nama Aset]",
    glAdjustExpenseNote: "Penyesuaian Investasi (Rugi): [Nama Aset]",
    initialAssetNote: "Investasi Awal: [Nama Aset]",
    liquidateAssetNote: "Likuidasi Investasi: [Nama Aset]",
    emptyStats: "Belum ada data transaksi yang tercatat untuk dianalisis.",
    savings: "Tabungan",
    selectSavingGoal: "Pilih Target Tabungan",
    noSavingGoalsWarning: "Belum ada target tabungan yang dibuat. Buat target terlebih dahulu di menu Perencanaan.",
    savingNoteTemplate: "Menabung: [Nama Target]",
    budgetSuggestion: "Anggaran",
    historySuggestion: "Riwayat",
    budgetCategoryExists: "Anggaran untuk kategori ini sudah dibuat!",
    filterPeriod: "Filter Periode",
    daily: "Harian",
    weekly: "Mingguan",
    monthly: "Bulanan",
    quarterly: "Kuarter",
    yearly: "Tahunan",
    customPeriod: "Periode",
    startDate: "Dari",
    endDate: "Sampai",
    calendar: "Kalender",
    calendarSubtitle: "Analisis transaksi harian dalam bentuk kalender interaktif.",
    activeDays: "Hari Aktif",
    activeDaysDesc: "Hari dengan aktivitas arus kas",
    noTransactionsDate: "Tidak ada transaksi tercatat pada tanggal ini.",
    addTransactionDate: "Tambah Transaksi pada",
    customDateTransaction: "Catat di Tanggal Terpilih",
    settings: "Pengaturan",
    settingsSubtitle: "Sesuaikan preferensi aplikasi Anda di sini.",
    settingsComingSoon: "Fitur ini sedang dalam pengembangan",
    settingsAccount: "Pengaturan Akun & Keamanan",
    settingsPreferences: "Preferensi Sistem",
    settingsBackup: "Cadangan & Ekspor Data",
    settingsGeneral: "Umum",
    settingsCurrency: "Mata Uang Utama",
    settingsTheme: "Tema Tampilan",
    settingsLanguage: "Bahasa Default",
    settingsNotifications: "Notifikasi Arus Kas",
    // --- Auto Logging ---
    autoLog: "Transaksi Berulang",
    autoLogSubtitle: "Jadwalkan pengeluaran atau pemasukan rutin yang akan otomatis tercatat.",
    addRule: "Tambah Aturan",
    editRule: "Edit Aturan",
    deleteRule: "Hapus Aturan",
    deleteRuleConfirm: "Hapus aturan transaksi berulang ini?",
    ruleTitle: "Nama Transaksi",
    ruleTitlePlaceholder: "Contoh: Bayar Netflix, Gaji Masuk",
    ruleAmount: "Nominal (Rp)",
    ruleFrequency: "Frekuensi",
    ruleStartDate: "Mulai Berlaku",
    ruleCategory: "Kategori",
    ruleNote: "Catatan",
    ruleType: "Jenis",
    ruleActive: "Aktif",
    ruleInactive: "Nonaktif",
    emptyAutoLog: "Belum ada aturan transaksi berulang. Tambahkan aturan untuk mencatat transaksi rutin secara otomatis.",
    freqDaily: "Harian",
    freqWeekly: "Mingguan",
    freqMonthly: "Bulanan",
    freqYearly: "Tahunan",
    autoLogExecuted: "transaksi otomatis telah dicatat",
    toastTxAdded: "Transaksi berhasil ditambahkan!",
    toastTxDeleted: "Transaksi dihapus.",
    toastGoalAdded: "Target tabungan berhasil dibuat!",
    toastGoalUpdated: "Target tabungan berhasil diperbarui!",
    toastRuleAdded: "Aturan transaksi berulang berhasil disimpan!",
    toastRuleDeleted: "Aturan dihapus.",
    toastSaved: "Perubahan berhasil disimpan!",
    // --- Average Analysis ---
    trendAnalysis: "Analisis Tren",
    averageAnalysis: "Analisis Rata-rata",
    averageMonthlyIncome: "Pemasukan",
    averageMonthlyExpense: "Pengeluaran",
    averageTransactionValue: "Nilai per Transaksi",
    avgMonthlySavings: "Selisih Bersih",
    savingsRate: "Rasio Tabungan",
    expenseEfficiency: "Efisiensi Anggaran",
    auditorAssessment: "Penilaian Auditor",
    variance: "Varians",
    usage: "Penggunaan",
    financialHealthScore: "Skor Kesehatan Finansial",
    auditComment: "Komentar Audit",
    categoryComparison: "Perbandingan Transaksi Batas Anggaran",
    auditorScoreCard: "Kartu Skor Auditor Keuangan",
    budgetLimitLabel: "Batas Anggaran",
    actualAverage: "Rata-rata Aktual",
    netVariance: "Varians Bersih",
    status: "Status",
    optimal: "Optimal",
    frugal: "Hemat",
    overbudget: "Overbudget",
    critical: "Kritis",
    healthExcellent: "Sangat Baik",
    healthGood: "Baik",
    healthFair: "Cukup",
    healthPoor: "Kurang",
    healthCritical: "Kritis",
    budgetCompliance: "Kepatuhan Anggaran",
    cashFlowVolatility: "Volatilitas Arus Kas",
    savingsRateDesc: "Persentase pemasukan yang tidak terpakai. Semakin tinggi, semakin banyak uang yang bisa ditabung.",
    budgetComplianceDesc: "Proporsi kategori yang tidak melebihi anggaran. Semakin mendekati 100%, semakin disiplin.",
    cashFlowVolatilityDesc: "Tingkat kestabilan pengeluaran harian. Semakin rendah (mendekati 0%), semakin stabil pola keuangan.",
    noBudgetData: "Belum ada data anggaran. Atur batas anggaran di menu Perencanaan untuk perbandingan.",
    auditScoreDesc: "Skor ini dihitung berdasarkan rasio tabungan, kepatuhan anggaran, dan stabilitas arus kas Anda.",
    auditorReviewTitle: "Laporan Audit Keuangan",
    totalTransactions: "Total Transaksi",
    periodAverage: "Rata-rata Periode",
    monthlyAverage: "Rata-rata Bulanan",
    dailyAverage: "Rata-rata harian",
    rateLabel: "Rasio",
    budgetDetail: "Rincian Anggaran",
    periodBudget: "Batas Anggaran",
    periodActual: "Realisasi",
    unbudgetedCategories: "Kategori Tanpa Anggaran",
    transactionFrequency: "Frekuensi Transaksi",
    avgPerTx: "Rata-rata per Transaksi",
    chartBar: "Grafik Batang",
    chartPie: "Diagram Lingkaran",
  },
  en: {
    dashboard: "Dashboard",
    dashboardSubtitle: "Your financial summary today.",
    totalBalance: "Total Balance",
    income: "Income",
    expense: "Expense",
    cashFlow: "Cash Flow",
    recentTransactions: "Recent Transactions",
    history: "Transaction History",
    historySubtitle: "A complete list of all your transactions.",
    allTransactions: "All Transactions",
    date: "Date",
    category: "Category",
    note: "Note",
    amount: "Amount",
    noTransactions: "No transactions recorded yet.",
    quickEntry: "Quick Entry",
    addNewTransaction: "Add New Transaction",
    modalDesc: "Enter your transaction details for today.",
    amountLabel: "Amount (Rp)",
    categoryLabel: "Category",
    noteLabel: "Note",
    categoryPlaceholder: "Food, Transport, etc.",
    notePlaceholder: "Lunch",
    cancel: "Cancel",
    save: "Save Transaction",
    today: "Today",
    yesterday: "Yesterday",
    daysAgo: "Days ago",
    currentTotal: "Current balance",
    overallTotal: "Overall total",
    initialBalance: "Initial Balance",
    initialNote: "Initial capital",
    livePreview: "Amount Preview:",
    inputNumberWarning: "Please enter numbers only",
    planning: "Planning",
    planningSubtitle: "Manage your budget limits & saving goals.",
    statistics: "Statistics",
    statisticsSubtitle: "Analyze charts of your cash flow & expenses.",
    netWorth: "Net Worth",
    totalInvestment: "Total Investment",
    cashBalance: "Cash Balance",
    portfolioAsset: "Total Portfolio & Asset",
    stocks: "Stocks",
    crypto: "Crypto",
    initialCapital: "Initial Capital",
    realizedGainLoss: "Realized Gain / Loss",
    netInvestmentValue: "Net Investment Value",
    profit: "Profit",
    loss: "Loss",
    updatePortfolio: "Update Portfolio",
    weeklyReminder: "Weekly Reminder",
    weeklyReminderDesc: "Update the realized gain/loss of your Stocks & Crypto investments this week for accurate net worth calculation.",
    lastUpdated: "Last updated",
    budgetLimit: "Budget Limits",
    savingGoals: "Saving Goals",
    cashFlowTrend: "Cash Flow Trend (Income vs Expense)",
    topExpenses: "Top Expenses",
    activeLabel: "Active",
    targetLabel: "Target",
    collectedLabel: "Collected",
    remainingLabel: "Remaining",
    saveChanges: "Save Changes",
    incomeVsExpense: "Income vs Expense",
    loading: "Loading...",
    addAsset: "Add New Asset",
    assetName: "Asset Name",
    assetType: "Asset Type",
    otherType: "Other",
    weeklyRecommended: "Weekly Update Recommended",
    noAssets: "No investment assets recorded.",
    deleteAssetConfirm: "Delete this asset?",
    editAsset: "Edit Asset",
    newAsset: "New Asset",
    allAssetsDetail: "Portfolio & Asset Allocation Details",
    addBudget: "Add Budget Limit",
    editBudget: "Edit Budget Limit",
    deleteBudgetConfirm: "Delete this budget limit?",
    budgetCategory: "Budget Category",
    budgetAmount: "Budget Limit (Rp)",
    addGoal: "Add Saving Goal",
    editGoal: "Edit Saving Goal",
    deleteGoalConfirm: "Delete this saving goal?",
    goalTitle: "Saving Goal Name",
    goalTarget: "Target Amount (Rp)",
    goalCollected: "Collected Amount (Rp)",
    goalIcon: "Select Icon",
    emptyBudgets: "No budget limits set. Set monthly budget limits to prevent overspending.",
    emptyGoals: "No saving goals defined. Set your dream goals and track your saving milestones regularly.",
    newBudget: "New Budget Limit",
    newGoal: "New Saving Goal",
    allBudgets: "Manage Budget Limits",
    allGoals: "Manage Saving Goals",
    deleteConfirm: "Are you sure you want to delete this?",
    deleteBudget: "Delete Budget",
    deleteGoal: "Delete Goal",
    deductFromCash: "Deduct from Cash Balance",
    deductHelp: "Deduct your active cash balance for asset's initial capital.",
    glAdjustNote: "The realized gain/loss difference will be recorded automatically as a transaction.",
    liquidateConfirm: "Asset Deletion & Liquidation Options",
    liquidateDesc: "The current net value of this asset is [value]. Would you like to liquidate this remaining value back into your Cash Balance (recording an Income transaction)?",
    liquidateOption: "Yes, Liquidate to Cash",
    deleteOnlyOption: "Delete Only (No Liquidation)",
    glAdjustIncomeNote: "Investment Adjustment (Gain): [Nama Aset]",
    glAdjustExpenseNote: "Investment Adjustment (Loss): [Nama Aset]",
    initialAssetNote: "Initial Investment: [Nama Aset]",
    liquidateAssetNote: "Investment Liquidation: [Nama Aset]",
    emptyStats: "No transaction records available for analysis yet.",
    savings: "Savings",
    selectSavingGoal: "Select Saving Goal",
    noSavingGoalsWarning: "No saving goals created yet. Create a goal first in the Planning menu.",
    savingNoteTemplate: "Saving: [Goal Name]",
    budgetSuggestion: "Budget",
    historySuggestion: "History",
    budgetCategoryExists: "Budget limit for this category has already been created!",
    filterPeriod: "Filter Period",
    daily: "Daily",
    weekly: "Weekly",
    monthly: "Monthly",
    quarterly: "Quarterly",
    yearly: "Yearly",
    customPeriod: "Specific Period",
    startDate: "From",
    endDate: "To",
    calendar: "Calendar",
    calendarSubtitle: "Analyze daily transactions in an interactive calendar grid.",
    activeDays: "Active Days",
    activeDaysDesc: "Days with cash flow activity",
    noTransactionsDate: "No transactions recorded on this date.",
    addTransactionDate: "Add Transaction on",
    customDateTransaction: "Record on Selected Date",
    settings: "Settings",
    settingsSubtitle: "Customize your application preferences here.",
    settingsComingSoon: "This feature is under development",
    settingsAccount: "Account & Security Settings",
    settingsPreferences: "System Preferences",
    settingsBackup: "Backup & Data Export",
    settingsGeneral: "General",
    settingsCurrency: "Primary Currency",
    settingsTheme: "Display Theme",
    settingsLanguage: "Default Language",
    settingsNotifications: "Cash Flow Notifications",
    // --- Auto Logging ---
    autoLog: "Recurring Transactions",
    autoLogSubtitle: "Schedule routine income or expense entries to be recorded automatically.",
    addRule: "Add Rule",
    editRule: "Edit Rule",
    deleteRule: "Delete Rule",
    deleteRuleConfirm: "Delete this recurring transaction rule?",
    ruleTitle: "Transaction Name",
    ruleTitlePlaceholder: "e.g. Netflix Subscription, Monthly Salary",
    ruleAmount: "Amount (Rp)",
    ruleFrequency: "Frequency",
    ruleStartDate: "Start Date",
    ruleCategory: "Category",
    ruleNote: "Note",
    ruleType: "Type",
    ruleActive: "Active",
    ruleInactive: "Inactive",
    emptyAutoLog: "No recurring rules yet. Add a rule to automatically log routine transactions.",
    freqDaily: "Daily",
    freqWeekly: "Weekly",
    freqMonthly: "Monthly",
    freqYearly: "Yearly",
    autoLogExecuted: "automatic transactions have been recorded",
    toastTxAdded: "Transaction added successfully!",
    toastTxDeleted: "Transaction deleted.",
    toastGoalAdded: "Saving goal created successfully!",
    toastGoalUpdated: "Saving goal updated successfully!",
    toastRuleAdded: "Recurring rule saved successfully!",
    toastRuleDeleted: "Rule deleted.",
    toastSaved: "Changes saved successfully!",
    // --- Average Analysis ---
    trendAnalysis: "Trend Analysis",
    averageAnalysis: "Average Analysis",
    averageMonthlyIncome: "Income",
    averageMonthlyExpense: "Expense",
    averageTransactionValue: "Per Transaction",
    avgMonthlySavings: "Net Balance",
    savingsRate: "Savings Rate",
    expenseEfficiency: "Expense Efficiency",
    auditorAssessment: "Auditor Assessment",
    variance: "Variance",
    usage: "Usage",
    financialHealthScore: "Financial Health Score",
    auditComment: "Audit Comment",
    categoryComparison: "Budget Transaction Comparison",
    auditorScoreCard: "Financial Auditor Scorecard",
    budgetLimitLabel: "Budget Limit",
    actualAverage: "Actual Average",
    netVariance: "Net Variance",
    status: "Status",
    optimal: "Optimal",
    frugal: "Frugal",
    overbudget: "Overbudget",
    critical: "Critical",
    healthExcellent: "Excellent",
    healthGood: "Good",
    healthFair: "Fair",
    healthPoor: "Poor",
    healthCritical: "Critical",
    budgetCompliance: "Budget Compliance",
    cashFlowVolatility: "Cash Flow Volatility",
    savingsRateDesc: "Percentage of income not spent. Higher means more money saved.",
    budgetComplianceDesc: "Proportion of categories within budget. Closer to 100% means more disciplined.",
    cashFlowVolatilityDesc: "Stability of daily expenses. Lower (closer to 0%) means more stable finances.",
    noBudgetData: "No budget data yet. Set budget limits in the Planning menu for comparison.",
    auditScoreDesc: "This score is calculated based on your savings rate, budget compliance, and cash flow stability.",
    auditorReviewTitle: "Financial Audit Report",
    totalTransactions: "Total Transactions",
    periodAverage: "Period Average",
    monthlyAverage: "Monthly Average",
    dailyAverage: "Daily avg",
    rateLabel: "Rate",
    budgetDetail: "Budget Details",
    periodBudget: "Period Budget",
    periodActual: "Actual",
    unbudgetedCategories: "Unbudgeted Categories",
    transactionFrequency: "Transaction Frequency",
    avgPerTx: "Avg per Transaction",
    chartBar: "Bar Chart",
    chartPie: "Pie Chart",
  }
}

interface LanguageState {
  language: Language
  setLanguage: (language: Language) => void
}

export const useLanguageStore = create<LanguageState>()(
  persist(
    (set) => ({
      language: 'id',
      setLanguage: (language) => set({ language }),
    }),
    {
      name: 'cashhero-language',
    }
  )
)
